version: '3.1'
services:

  web:
    build: .
    command: ng serve --host 0.0.0.0
    container_name: videomegoszto_web
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 4200:4200
